### ISSUE TITLE
Add hook for sidebar cell titles for i18n

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/draw.io#1]
Replace hard-coded strings with calls to hook passing in a key. For now, just resolve the keys back to the existing English strings.

**Comment by alderg** [comment]
Override Sidebar.createItem and replace title argument with translation as follows:

`(function()
{
	var sidebarCreateItem = Sidebar.prototype.createItem;
	
	Sidebar.prototype.createItem = function(cells, title, showLabel, showTitle, width, height, allowCellsInserted)
	{
		title = 'Translated ' + title; /* Translate title */
		
		return sidebarCreateItem.apply(this, arguments);
	};
})();`

**Comment by alderg** [comment]
Override Sidebar.createItem and replace title argument with translation as follows:

    (function()
    {
      var sidebarCreateItem = Sidebar.prototype.createItem;
	
      Sidebar.prototype.createItem = function(cells, title, showLabel, showTitle, width, height, allowCellsInserted)
      {
        title = 'Translated ' + title; /* Translate title */
		
        return sidebarCreateItem.apply(this, arguments);
      };
    })();
