### ISSUE TITLE
Add Nextcloud as storage option?

### ISSUE THREAD

**Issue by poVoq** [jgraph/draw.io#10]
Would be great to be able to add our own custom cloud with Nextcloud (or Owncloud) as a storage option?

**Comment by davidjgraph** [comment]
We did create an owncloud 7 plugin, but v8 came out a few weeks later and the plugin was broken. This isn't the kind of ecosystem we're inclined to write for if they introduce random breaking changes within documentation. Other users have asked, https://help.nextcloud.com/t/make-draw-io-plugin-work-again/3958, on the specific forums. It will need to be a community contribution, we're not going to waste our time again.

**Comment by michaelnew** [comment]
What about just supporting WebDAV storage? That way there's no reliance on the whims of Owncloud/Nextcloud and it works as a more general solution.

**Comment by davidjgraph** [comment]
https://support.draw.io/pages/viewpage.action?pageId=7504018

**Comment by alderg** [comment]
https://github.com/jgraph/drawio-webdav

**Comment by davidjgraph** [comment]
https://github.com/pawelrojek/nextcloud-drawio
