### ISSUE TITLE
[Bug] Background changes to not enter the undo buffer

### ISSUE THREAD

**Issue by pensono** [jgraph/draw.io#105]
Steps to reproduce:
1. Open a new document
2. Add a shape to the document
3. Change the background to some color
4. Add a shape to the document
5. Undo twice

Expected:
The document contains only one shape with a white background.

Actual:
The document contains no shapes with a background.

Not a huge issue, but a bug none the less. There are also other places where the same sort of thing happens, often with checkboxes in the properties panel. The checkbox for the background is another example.

**Comment by jackyjsy** [comment]
Yes. I can reproduce this issue. If background changes can be recorded by undo buffer, it will be great!

**Comment by alderg** [comment]
This will be fixed in the next release.
