### ISSUE TITLE
running draw.io from local file system fails in Chrome and Electron

### ISSUE THREAD

**Issue by jdittrich** [jgraph/draw.io#11]
Story: As a user I want to run draw.io locally, ideally also without an internet connection.

## Using Chrome/Chromium

**What I tried:**
1. I cloned the git repo and went to the *war* folder.
1. I opened index.html or app.html using chrome. 

**What I expected:** I expected to see the where-do-you-want-to-save screen and, afterwards, the draw.io application

**What happened:**
* Chrome displayed the content of the index.html- page (Flowchart Maker and Online Diagram Software […] Loading... Please ensure JavaScript is enabled )
* on the devtools console, I got

```
app.min.js:325 XMLHttpRequest cannot load file:///home/[somefolders]/draw.io/war/stencils.xml. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.mxXmlRequest.send @ app.min.js:325
app.min.js:325

Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///home/[somefolders]/draw.io/war/stencils.xml'.
```
*I tried using Firefox instead, there it works without errors – I can use draw.io there without problems*

(On Firefox 49.0, and Chromium 53.0.2785.143; running on Ubuntu 16.04 (64-bit))

## Via HTTP-Server

**What I tried:** I tried to run *draw.io* on a local server (via `python -m SimpleHTTPServer`): 

**What happened** 

It worked in non of the browsers: 

* **In Firefox:** SSL_ERROR_RX_RECORD_TOO_LONG
* **In Chrome:** ERR_SSL_PROTOCOL_ERROR <br>
while the server says: `code 400, message Bad request version` after some (base64?) encoded lines which start right after "/images/logo-confluence.png" is loaded. 

(same browser versions and OS as above)

## Via Electron
**What I tried** 

1. in the *war* folder, I ran `npm install`
2. npm start

**What happened:** As on Chrome, it never got beyond the initial page as it seemed to be unable to access needed javascript files, e.g.  file:///home/[somefolders]/mxgraph2/javascript/src/js/mxClient.js. 

Note that the repo was cloned into file:///home/[somefolders]/draw.io/ initially, so the file looked for is not even searched for in the repo. 

--------------

Sorry for the long issue, I hope the descriptions are clear enough. Also, if you need any more extensive log files, I can provide those too.

**Comment by alderg** [comment]
Try disable SSL via ?https=0 using the local web server.

**Comment by jdittrich** [comment]
thanks, that worked! – I'd gladly provide a description of how-to-run-locally for wiki or readme, whatver you prefer so that others can resolve this themselves. (For the wiki, I don't know what your preferred process would be, since it currently does not allow editing for me; for the readme I would send a pull request)

**Comment by alderg** [comment]
Probably best to add to the README.

**Comment by jdittrich** [comment]
@alderg – is possible that editing is switched of for this wiki? 
In contrast to other github wikis, the *edit* button is missing for me.

**Comment by alderg** [comment]
True. Paste the text here and we'll add it. Thanks!

**Comment by jdittrich** [comment]
If you want to run *draw.io* locally you can:
* Run it in Firefox by opening the index.html. You can add the *index.html?offline=1* parameter to suppress the cloud based saving options.
* Run it in Firefox or Chrome by 
 1. Running a local http server (e.g.  pythons `python -m SimpleHTTPServer 8000`)  in the `/war` directory. 
 2. Then open the *draw.io*’s`index.html`with the parameters `offline=1` and `https=0`, (e.g. `http://localhost:8000/index.html?offline=1&https=0`)

**Comment by davidjgraph** [comment]
To add to this, not being able to make XHR calls in JS when loaded by file: protocol is a standard known limitation of JS app deployment. I don't really want to turn the wiki into a general JS tutorial, though I understand the value of this hint to someone that doesn't know it.

Via http server, in the first post, it sounds like the SSL wasn't configured properly. Again, this isn't really specific to draw.io.

The Electron build does work. You need to grab https://github.com/jgraph/mxgraph into a folder called "mxgraph2" and for mxgraph2 to be a sibling folder of the draw.io checkout.

**Comment by jdittrich** [comment]
Thanks! I understand the concern of adding seemingly redundant information to the wiki. If I understand you right, you assume that adding the information about parameters and running a server is such redundant information. 

If one is already knowledgeable about  *draw.io*’s inner workings I can understand that the it may feel like redundant information. 

However, people who run the software (also to get to know its code better!) are not aware of the ways draw.io runs and specifically, gets its files. For them, knowing the parameters, and the need for a http-server are important. Same goes for getting mxdraw and naming it mxdraw2 to run in dev mode. 

I know a fair share about JS and the need to https etc., however, I was unable to solve it without your help and instructions can help people like me to contribute in a way that helps us as well as draw.io

**Comment by davidjgraph** [comment]
The wiki is publicly editable, have a try at improving it, worse case I'll tweak it a tiny bit :).

**Comment by jdittrich** [comment]
great. I do!

**Comment by davidjgraph** [comment]
Could you also drop me an email david@jgraph.com? I'm trying to gather more high level details on what people need from draw.io as a project and it doesn't really belong in an issue chat.

**Comment by adamfakrullah** [comment]
how to disable disable SSL via ?https=0 using the local web server?

**Comment by jdittrich** [comment]
@adamfakrullah 
>how to disable disable SSL via ?https=0

You attach the parameter to the web address:

>  * … open the draw.io’s index.htmlwith the parameters offline=1 and https=0, (e.g. http://localhost:8000/index.html?offline=1&https=0)

**Comment by adamfakrullah** [comment]
Sorry, can i know steps for run java part about mxgraph in eclipse because i cannot run the main java. the folder link is https://github.com/jgraph/mxgraph. I hope u you can help me because it is important for my final project.

**Comment by jdittrich** [comment]
@adamfakrullah 
Assuming from your reply – you try to run draw.io in Java? 

Did you already read https://jgraph.github.io/mxgraph/java/index.html ? 

Is there any error message?

**Comment by adamfakrullah** [comment]
![eclipse](https://user-images.githubusercontent.com/23518461/32379640-0897a2d4-c0e9-11e7-8d40-dba0dd626192.png)

This errors. I dont have idea to solve it.sorryy

**Comment by davidjgraph** [comment]
You're trying to run an a Java Swing example from the mxGraph project, this is completely unrelated, you are posting to the wrong project.

**Comment by adamfakrullah** [comment]
I just want to try GraphEditor - Full-featured graph editor example from https://jgraph.github.io/mxgraph/java/index.html  so i try to run it but it shows error

**Comment by davidjgraph** [comment]
Again, this isn't the mxGraph project, you are posting in the wrong project, please stop.

**Comment by CholoTook** [comment]
Hi, I don't get to the part where the App starts, it already fails with this error:

> draw.io@13.3.1 start /home/dbolser/Build/drawio-desktop-13.3.1
> electron ./drawio/src/main/webapp

Error launching app
Unable to find Electron app at /home/dbolser/Build/drawio-desktop-13.3.1/drawio/src/main/webapp

Cannot find module '/home/dbolser/Build/drawio-desktop-13.3.1/drawio/src/main/webapp'
Require stack:
- /home/dbolser/Build/drawio-desktop-13.3.1/node_modules/electron/dist/resources/default_app.asar/main.js
- 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draw.io@13.3.1 start: `electron ./drawio/src/main/webapp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the draw.io@13.3.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dbolser/.npm/_logs/2020-06-25T14_37_44_091Z-debug.log

**Comment by CholoTook** [comment]
Thanks for any help
