### ISSUE TITLE
Nextcloud Integration Issue (page does not load)

### ISSUE THREAD

**Issue by mbelton** [jgraph/draw.io#110]
My company created a server for draw so we could integrate it with our Nextcloud instance.

The application loads great when you connect directly but the issue is when trying to open a saved .xml file from Nextcloud. 

Once you click the icon for the file, a tab opens and the page only loads the banner with all options grayed out except File and Help. The loading icon also hangs in the center and does not advance.

Where should we look to correct this?

**Comment by davidjgraph** [comment]
https://github.com/pawelrojek/nextcloud-drawio is the project for the integration, they are not related to us.
