### ISSUE TITLE
Doesn't save when using git account

### ISSUE THREAD

**Issue by Zinkutal** [jgraph/draw.io#111]
After initial commit if u close or get to previous page, no changes are being saved. It is a very bad experience. Add some temporary file or smth else. Or just any alert message.

**Comment by alderg** [comment]
Not sure what you mean, can you please clarify: What are the exact steps to reproduce the problem? What is the expected and what is the actual output?

**Comment by Zinkutal** [comment]
@alderg Just login only via GitHub account. Save button will appear(to commit yours actions). Problem occurs when you have done some actions and then you go to one page back. All changes are reset without ability to restore them. What I want is that this gonna be temporary saved without doing actual commit or alert message saying that all changes will be reset if you will accidentally close tab. This bug doesn't occur when you're logged in via Google account, cause it is saving all changes.

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
