### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by steven10172** [jgraph/draw.io#112]
I just noticed that you changed the license for the project and would like to say Thank You!

After auditing the other code I noticed that you might have forgot to update the license change in the electron package.json file. Can you update that? https://github.com/jgraph/draw.io/blob/master/etc/electron/package.json#L20

I would also like to point out that the project uses jscolor which has a GPL-3 license. Can the code be updated to use the native color picker? (I don't think Apache license projects can properly consume GPL-3 license projects due to it's restrictive licensing)
 https://github.com/jgraph/draw.io/tree/master/war/js/jscolor

**Comment by davidjgraph** [comment]
jscolor see https://github.com/jgraph/mxgraph/issues/80.

We'll fix the electron licensing, thanks for the pointer.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/draw.io/commit/754dc2399ce73cdef1580f5cec0aad842faabb7f

**Comment by spectejb** [comment]
Can you also update the text in v6.5.6 to be the Apache 2.0 license text?  (https://github.com/jgraph/drawio/blob/v6.5.6/LICENSE)

The license title says Apache 2.0 but the text is GPL 3.0.  The readme file also says GPL 3.0.  

Thanks, in advance, for your help!
