### ISSUE TITLE
[Feature Request] Night Mode/Theme

### ISSUE THREAD

**Issue by Shinigami92** [jgraph/draw.io#113]
A dark gray theme for night mode that doesn't hurt the eyes so much.

**Comment by alderg** [comment]
Feature requests go here: https://draw.uservoice.com/forums/266072-feature-requests

**Comment by Shinigami92** [comment]
Thx, I will leave this for reference: https://draw.uservoice.com/forums/266072-feature-requests/suggestions/13087449-dark-theme
