### ISSUE TITLE
GraphSketcher

### ISSUE THREAD

**Issue by RoyiAvital** [jgraph/draw.io#116]
Hello,

Could you incorporate the features of [GraphSketcher](https://github.com/graphsketcher/GraphSketcher) into draw.io?

This will be a killer feature.

Moreover, could you option to rotate a line form the menu (Set the angle with numbers).
Better allow to set the anchor point for the rotation (Start, Middle, End).

Thank You.

**Comment by davidjgraph** [comment]
We can't, no, it's native code.

**Comment by RoyiAvital** [comment]
What about its capabilities?

It is something no one else offer out there.

**Comment by RoyiAvital** [comment]
By the way, any chance you add "Release Notes" for Releases?

**Comment by RoyiAvital** [comment]
Another option would the Geometry part of [GeoGebra](https://www.geogebra.org).
