### ISSUE TITLE
[feature request] UML doesn't provide the implimentation notation 

### ISSUE THREAD

**Issue by brownlincoln** [jgraph/draw.io#119]
There are many relations notations in UML, see https://en.wikipedia.org/wiki/File:Uml_classes_en.svg  . But I can't find the implementation notations in https://www.draw.io   -- UML .

**Comment by alderg** [comment]
https://www.draw.io/#RjVNNb4MwDP013IG0VXfcWNtdKlXisHNKXIga4iqYfuzXLzQJH0PTxgHiZ%2FvZ8TMRy%2Br7zvBLtUcBKkpjcY%2FYe5SmL6ulfXfAwwErtnZAaaRwUDIAufwCD8YebaWAZhJIiIrkZQoWqDUUNMG4MXibhp1QTateeAkzIC%2B4mqOfUlDl0PUyHvAPkGUVKi9i7zny4lwabLWvF6Xs9Hycu%2BaBy8c3FRd4G0FsE7HMIJI71fcMVDfaMDaXt%2F3F2%2FdtQNN%2FEphLuHLVQuj42Rc9wixAi9dupNY6KizOEXurqFbWTOzxhJq2vJaqUzrDWhY2O%2Be6sZ997gO8wMnC2pZuK1WXHjsrONfWFLypQHjqzjhwIjDaInaB4i7E9QdiJuBw5aQfpN1PwBrIPGzIbVAyCFmNRAyYAcVJXqf03C9U2dP1FQ4obeE09rufhlXwq58EqQNFg60pwGeNpflBxFZ%2FEBE3JdCMyB5G1x6gp%2FLBHDbMhQ9%2FMdt8Aw%3D%3D

**Comment by brownlincoln** [comment]
![notations](https://user-images.githubusercontent.com/16752841/27010909-567b56fe-4ee2-11e7-9e2a-057c5ce9bfcd.PNG)   Yes, we can draw this kind of arrow, but it is not a direct way. I mean, in the picutre, there is no this kind of arrow.

**Comment by alderg** [comment]
Good point. Will be added in the next release.
