### ISSUE TITLE
web server draw.io process 

### ISSUE THREAD

**Issue by capocchi** [jgraph/draw.io#120]
Dear all,
i want to execute draw.io on a web server and extend the user interface adding some ne fonctionnalities (like new export format). I dont reach to identify the sources to udpate and dont know if there is possible to do this in inline mode. 

Thanks for your help.

**Comment by davidjgraph** [comment]
Issues are for specific bugs, not general discussion.

**Comment by capocchi** [comment]
How to post request for general discussion?
