### ISSUE TITLE
Embed -> iFrame creates broken link to edit drawing

### ISSUE THREAD

**Issue by Destrukto** [jgraph/draw.io#123]
If you go to FIle -> Embed -> iFrame the link has a "edit=_blank" in it.
Till now, there was a link on the diagram (something like "edit=https%3A%2F%2Fwww.draw.io%2F....). 
So now the embedded diagram cannot be edited, it creates a copy of the diagram in a new file.

Tested on Chrome  58.0.3029.110 (64-bit).

**Comment by alderg** [comment]
If the diagram is public (Sharing settings in Google Drive), the link will change automatically.

**Comment by Destrukto** [comment]
the problem with this is, that if I have shared the diagram with selected people they can't edit it.
In my environment it makes no sense that everybody can edit a diagram.

**Comment by alderg** [comment]
So you want a copy to be shown in the lightbox but when they click edit, they edit the real diagram (if they have access), correct?
There is no option in the UI for this exact case currently, but you can use the current address in the browser and replace _blank after edit= with its URL encoded value, which can be obtained by using http://jgraph.github.io/drawio-tools/tools/convert.html, pasting the address and click "URL encode".

**Comment by Destrukto** [comment]
This was working in an earlier version of draw.io. The link actually had the URL in the edit=... part of the URL and as a workaround I can manually edit the URL. But why has this changed?

**Comment by alderg** [comment]
People didn't like the login screen.

**Comment by Destrukto** [comment]
Is there a possibility to support both?

**Comment by alderg** [comment]
Yeah, we'll add a custom edit option.

**Comment by Destrukto** [comment]
great thanks
