### ISSUE TITLE
Is draw.io trees available offline?

### ISSUE THREAD

**Issue by Losiara** [jgraph/draw.io#125]
I ve downloaded github repo and run it in electron but mindmap figures can find only here https://www.draw.io/?p=trees 
I also see it in plugins dir but how to activate it offline?

PS
In extras menu I have no "plugin" elem.

**Comment by davidjgraph** [comment]
You need to add another plugin URL parameter to the electron launch URL https://github.com/jgraph/draw.io/blob/master/etc/electron/electron.js#L50 , i.e.:

`	'p': 'trees',`

in addition to what's already there.
