### ISSUE TITLE
Error when run cmd "electron ."

### ISSUE THREAD

**Issue by Losiara** [jgraph/draw.io#126]
I run draw.io on electron by this command

```electron war/index.html```

If I do 
``` electron .``` I have an error:

```
Syntax Errror Microsoft js compiler
Code 800A03EA
```

**Comment by davidjgraph** [comment]
In etc/electron do:
`npm install`
`npm start`

**Comment by Losiara** [comment]
I did - the same error.

**Comment by davidjgraph** [comment]
I've never tried it on Windows. Did you Google the error?

**Comment by Losiara** [comment]
Tried! Exactly thee same code did not find. Similar error caused by electron and also packages - no details, sorry.

I can run app from higher level dir in the elctron, but plugin submenu not available this way.
