### ISSUE TITLE
PDF export does not include emoji

### ISSUE THREAD

**Issue by pietrodn** [jgraph/draw.io#127]
Steps to reproduce:
1. Open draw.io, new blank document
2. Draw a rectangle, add some text with an emoji to it
3. File -> Export -> PDF
4. Open the PDF with any viewer, emojis are not present

This happens with Safari and Chrome on macOS 10.12.
By using the "Print" function with Safari and exporting as PDF from the print dialog, emojis are preserved. The same trick doesn't work with Chrome.

**Comment by davidjgraph** [comment]
I'd expect this. The PDF generation servers won't have the right fonts to support smiley faces. I'm afraid you'll have to use your workaround.

**Comment by safaorhan** [comment]
I have the same problem. Anyone found any workaround?

**Comment by lemyx** [comment]
https://emoji.aranja.com/

Emoji -> png, then insert into draw.io diagrams.

**Comment by shaoyuyoung** [comment]
> https://emoji.aranja.com/
> 
> Emoji -> png, then insert into draw.io diagrams.

looks like a good solution. However, sometimes I can't find the specific style of emojis on https://emoji.aranja.com/. For example, this robot emoji 🤖 looks different on this website. :(
