### ISSUE TITLE
Edit an image shape always hangs the browser session

### ISSUE THREAD

**Issue by darren0h** [jgraph/draw.io#129]
For an image shape, which style code is like "shape=image;aspect=fixed;image=data:image/jpeg,".
When paste/import image into a draw.io project. The image will be showed in browser.
Then, when click the button "Edit Image". The inner popup dialog will show the image url with header and base64 code.
The bad thing is that, in this status, the browser session will lost response only if you click the "Esc" while it will recover after several seconds.
So, I think there is some bug in this part.
Fortunately, there is a workaround for this. You can view the base64 code in "Edit Style" dialog.

**Comment by alderg** [comment]
This will be fixed in the next release.
