### ISSUE TITLE
Different behaviour in new property validator (Chrome/IE) -> invalid XML

### ISSUE THREAD

**Issue by gollum1007** [jgraph/draw.io#130]
Hi,

it is possible to add a new meta data property with a name containing a colon ':' (in Google Chrome):
![image](https://user-images.githubusercontent.com/16134884/28115065-b767e566-6703-11e7-8e02-b71051be15b2.png)

This causes an XML parsing error in the uncompressed XML file because the attribute of the object has a name with an colon at the end:
![image](https://user-images.githubusercontent.com/16134884/28115084-c79f5860-6703-11e7-9574-36494c36400d.png)

The validator of the Internet Explorer prevents this.

I think there should be the same (self implemented) validator for all browsers or the invalid chars should be removed before saving or exporting to XML.

Thanks, Robin

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release. We've decided to check this specific case as we do want the DOM implementation to take care of the validation.
