### ISSUE TITLE
Line height 120 % problem not fixed (IE11 only)

### ISSUE THREAD

**Issue by gollum1007** [jgraph/draw.io#132]
Hello,

it seems that the 120 % problem with setting the line height in a shape is still present in IE 11.
![image](https://user-images.githubusercontent.com/16134884/28215833-ab449574-68af-11e7-866a-5815bdcf70ae.png)

It works in Chrome, Firefox and Edge.

Thanks, Robin

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
