### ISSUE TITLE
Matadata properties not sorted (IE11 only)

### ISSUE THREAD

**Issue by gollum1007** [jgraph/draw.io#133]
Hello,

the properties in the metadata Dialog should be sorted since 6.3.1:

12-MAR-2017: 6.3.1
- Sorts properties in metadata Dialog

Unfortunately not in IE11:
![image](https://user-images.githubusercontent.com/16134884/28260951-96a24e56-6add-11e7-9d90-3497a8a9b715.png)

Thanks

**Comment by alderg** [comment]
Good old IE 11. This will be fixed in the next release. Thanks for the report!
