### ISSUE TITLE
Feature: Insert image from system clipboard

### ISSUE THREAD

**Issue by jdittrich** [jgraph/draw.io#15]
**Story:** As a user, I want to insert images to *draw.io* quickly. 

It can be useful to be able to insert images from the clipboard to diagrams, e.g.:
* I want to improve an existing diagram and want to insert the old version for reference and documentation purposes.
* I want to create a mockup and want to reuse bits and pieces from a screenshot
* …

**Why clipboard?:** All can be done via image import, but export to image and importing it again is most often more cumbersome than Ctrl+C, Ctrl+V

**Match Google Docs/Confluence**: (image-)insert from system clipboard functions are available in google docs and in confluence, so users may be used to it already.

**Comment by alderg** [comment]
Works in Chrome.

**Comment by jdittrich** [comment]
Thanks for the info. Any change we might be able to find a cross browser solution? Or are these still depended of flash and other workarounds (I did not dissect the google docs implementation so far)?

**Comment by alderg** [comment]
No workarounds or flash used. Just checked in FF and it throws an error. The code is here: https://github.com/jgraph/draw.io/blob/master/war/js/diagramly/EditorUi.js#L3539

**Comment by jdittrich** [comment]
thanks, I hope I find the time to look at it.

**Comment by jdittrich** [comment]
…It seems to be coming with Firefox 50; before FF seems [not to support](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) the used items-array.
