### ISSUE TITLE
developing and debugging shape files

### ISSUE THREAD

**Issue by jdittrich** [jgraph/draw.io#16]
**Task:** I would like to build improve and/or add shapes (the kind with handles and other interactive functions which are defined in */war/shapes*)
**Problems:** 
* I was unable to use unminified versions of the shapes. 
* Is there any specific workflow for adding shapes? (It seems that at least the shape must be defined *and* a the setup in a *Sidebar-….js" file must take place, however there might be more to it)

**Comment by davidjgraph** [comment]
Run using the dev=1 URL parameter and the non-minified version of the code will be used. Note that you will need to map

`document.location.protocol + '//devhost.jgraph.com/mxgraph2'`

to the [mxGraph project](https://github.com/jgraph/mxgraph). We have mxGraph locallly, but I guess mapping it to Github should also work.

If you want things like handles, then yes, you'll need to implement in JS. You can follow the basic idea for the sidebar code, as you've seen. The build.xml does need to be updated, currently, for new additions. We probably should just wildcard that if the minifier allows it.

The other place stencils are referenced is in com.mxgraph.online.EmbedServlet2.initLibraries, which is the embed server-side code. If you're using embedding, you could override the class and add another init that calls this one.

**Comment by jdittrich** [comment]
Thanks, I’ll go with that!
If you paste it to the wiki it would be great since it would be easy to find for others (and me to refind it, too :smiley: )

**Comment by alderg** [comment]
See also: https://github.com/jgraph/mxgraph/blob/master/javascript/examples/grapheditor/www/js/Shapes.js
