### ISSUE TITLE
Save in offline mode appears to be broken in Safari

### ISSUE THREAD

**Issue by torkve** [jgraph/draw.io#18]
One of my colleagues faced a problem with save to device in Safari (as well as "export as xml").

As far as I found, [this branch](https://github.com/jgraph/draw.io/blob/master/war/js/diagramly/App.js#L5061) invokes real POST-request to the /save url.
It is opened in new tab and fails, since there's no such URL in offline application, and POST-requests are not supported when app is opened from disk or served by simple file-sharing server (like `python -m SimpleHTTPServer`). So the resulting xml cannot be saved.

**Comment by davidjgraph** [comment]
I'm not personally keen on offline mode in draw.io. Would fully tested Electron apps of draw.io work better for you?

**Comment by torkve** [comment]
Hm, I'm not sure. My use-case of offline mode is providing it as a safe intranet service, hence no third-party CDN, integrations with GDrive/Dropbox/OneDrive or any other requests including sending logs to draw.io itself.
Electron app currently lacks this feature and being unfamiliar with Node.JS and Electron, I don't see a way to ditribute and update app with Electron to every end user without NPM installation quest.

**Comment by davidjgraph** [comment]
Saving from Safari without using an echo server is a bit of a mess. You'll find discussions like [this one](http://stackoverflow.com/questions/12802109/download-blobs-locally-using-safari) on SO, but the upshot is there's no way to make it work on Safari 8,9 and 10, our supported Safari versions.

The most popular JS library for creating a shim is [FileSaver.js](https://github.com/eligrey/FileSaver.js/). You can see in the README that Safari is a problem. You can neither name the file and "sometimes" the blob is opened so you need users to ⌘+S to save.

Saving to file system in the browser is a fairly poor experience.That said, I see the advantage of distributing as a web app, the only way to solve this for Safari will be to have an echo on the server.

We can work out the exact parameters to switch everthing off without stopping comms to the local server, as well. I'd suggest starting with `?db=0&gapi=0&od=0&analytics=0&picker=0&mode=device&browser=0`. The logging changes are fairly recent, so it might be that we don't turn that off, we can add something for that.

Then you'd just need a simple echo for /save.

**Comment by davidjgraph** [comment]
You're welcome to continue the discussion, but I'll close the issue since it's not possible to do a local save of any reasonable kind in Safari.
