### ISSUE TITLE
Dropbox 401

### ISSUE THREAD

**Issue by muhammad-naderi** [jgraph/draw.io#20]
Hey, 

Thanks for the great work.

I use draw.io for multi level flowcharts, and connect an item in the parent flowchart to the details by a link to detail file in dropbox, when I do that, it just works fine, but when after some time I come back, open the master file in draw.io from my dropbox account, and in the master file click on a link to open the detail file  I get this error:

> Error (401)
> It seems you don't belong here! Check out our Help Center and forums for help, or head back to home.

seems to have something to do with dropbox implementation in draw.io, since it works well at the moment when I create the link, also the file still exist there, and when I edit the link, select the file from dropbox again, everything works fine, until some time later it all starts happening again.

**Comment by alderg** [comment]
This error means you're not authorized to view the file. What link are you using to reference the file, ie. is it a link to draw.io or dropbox.com?

**Comment by davidjgraph** [comment]
Please note we'd prefer general usage question on the [Google Group](https://groups.google.com/forum/#!forum/drawio) and to define the scope of Github issues as being development related.

**Comment by muhammad-naderi** [comment]
to create the link, 
I right-click on the item I want to link it, select Edit-Link, then Dropbox, and then from the dropbox window, I select my other draw.io file (which I saved earlier) ...
the result would be a dropbox link.
am I doing something wrong? or is it a problem with your implementation of dropbox api?!
