### ISSUE TITLE
Url parameter "offline=1" cause 'geSidebarTooltip' display unexpected

### ISSUE THREAD

**Issue by gsw945** [jgraph/draw.io#22]
I put **war** folder into my xampp web folder,then I visit it in firefox and chrome with url *http://localhost/war/index.html?offline=1&https=0* , but **SidebarTooltip** not displayed in normal position:
![feige20161025185705](https://cloud.githubusercontent.com/assets/6281968/19683598/692b5e90-9ae5-11e6-8c7e-4b309333ab2b.png)

Then, I changed the url parameter offline from 1 to 0, and then I removed it, **SidebarTooltip** displayed as we expected:
![feige2016102518999](https://cloud.githubusercontent.com/assets/6281968/19683771/49fdddd0-9ae6-11e6-8bba-0894899eb003.png)

At last, I try to access [https://jgraph.github.io/draw.io/war/index.html?offline=1](https://jgraph.github.io/draw.io/war/index.html?offline=1) ,there is the same bug, and it display notmally without parameter 'offline=1'.

**Comment by alderg** [comment]
Thanks for the report, this will be fixed in the next release.
