### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by Shmoo6000** [jgraph/draw.io#25]
For some reason the web-app won't let me change the font-size. The issue happens quite irregularly and unpredictably. I'm using Firefox 49.0.2 (Most recent version at the moment of writing). I don't seem to remember this happening while I was using the chrome extension. Here is a description of what exactly happens:
1. I double click to create a text box, default font size is 18 pt.
2. I type whatever I want in the text box.
3. I select all text in the text box.
4. I click the down arrow on the font size selector until the number is 12 pt.
5. I click outside of the text box to 'get rid of the menu'
6. The font size hasn't changed? (And doesn't change while adjusting the number)

When I manually enter a number and press enter to confirm the size doesn't change and when I reopen the text box settings the size is still 18 pt. It also impossible to change the font size on existing text boxes.

**Suggested Workaround:**
1. Go to 'Extras' -> 'Edit Diagram'
2. Copy to your favourite text-editor
3. Do a search for the text in your text box
4. Change the 'fontSize' property to the desired value
5. Copy and paste to 'Edit Diagram' window
6. Press OK
7. Font size should be fine now

This is the code to reproduce the diagram I believe
```xml
<mxfile userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0" version="6.0.1.0" editor="www.draw.io" type="device"><diagram name="Page-1">7Vzfc5s4EP5rPNN7cAZJ/PJj7LS9l850Jp2561OGYNlmgo0P48TpX38SSGBJUAMWFNPmJUgIAfvtt1rtLp6gxfb0Ofb2my/REocTaCxPE/QwgRCYlkH+0Z73rMexnKxjHQdLNqjoeAx+YNbJrlsfgyU+CAOTKAqTYC92+tFuh/1E6PPiOHoTh62iULzr3ltjpePR90K1959gmWxYL7BnxYm/cbDesFu70M5OPHv+yzqOjjt2vwlEq/QvO731+FzsRQ8bbxm9nXWhjxO0iKMoyY62pwUOqWy52LLrPlWczZ87xrukzgUwu+DVC4/s1eeLhyf4tCCvkOB4Au2QzDN/pkdrevQNqX3sVZJ3Lr63TZDgx73n0/YbUREyaJNsQ9IC5DCVD6ZPYJBWLgLaWIfe4cCO/Wgb+HxQEkcveBGFUZzeAhnpX36Go0QEOF8FYchH7qIdpl3RLmFaBugQLwzWO9LwcfqW/BXO5cZE+YrjBJ/OupgcP+Noi5P4nQxhZ3PlZToPXdZ+KzQIcmJszpQH2KzTY1q7zucukCMHDLxyIFFjIOEfIMuBtGANIM2ugDQbAwn+AFkOpFsHSLsrIC0FSAUVvFve09WKvjcVMxXuOSyiJIEkNpe0iXDi938pJHepGNP2dwZR2viK44A8O5Vp2lkp18SL1zgRlgW8FJZJVdBngiyzbLwvxqGXBK/i4lomW3aHr1FAHq6wrKaIoymhc4iOsY/ZReeL3YV5lIkyESgTpUjnb10L/FL0M5ZSCAU1sP87RvzE9JCCe08GAHN/Kk5yZh/e/fCFT0WeIputgvWEJ4lEdExu4D2nA6g27Om7pm9vzSfWQxkRKd8C4hrdsxPbYLmk189D7xmH89zhOTMFzOVR1VVVPi4nmdS5b8ceVvCPysg+Ne5cGwj4Ai3aNxUntZA4QbRaHfC16mI3shXMhDYyFJW0HyjHodGS5K57YSJ9JHf6sPBDB86yNQGnTOR2Bpzb89IMEdC3NpuDgv8i3VrzVvbB9ME/6wX+U5Bk6DsWa35nQythzmQ1SBfMkF2wljCjmSsup1ZnMCPVPif+0zekgD0oNwmWKghX2avdJOMOuYZWN0mrI8RjKMPmJhoUN5G0zTVnLbnpSCS3ujPBSF2CKTdVsG+Am7nOaiCnaRv2cMkJFNAGSM5h+UdIcmustgsnMIDVGztVD4myEyho3wI7q8KGbdjpQHHpRENiJ9TNTvsGt6NQ4psp7yJrBwtl4nZINzX8Qw5JxweiYOje+KtGgP8WmMgVVAMTgcVTsXy7qEV7plCYdGqLE+jhqZqq+xlPLwX7zN+ZpNalifSRFKiJuWtggzcImxyiuQnYmqXh2sBWOKwsznfmsdLj2lG+4XqxCvJy1KZtlK9L5PUmVS4gP4I4ApxJHg+4AXo3C+WP0Sp35vGa3aXHQT8h+CIDY8n5l0pUh1sGgZAYAGhdBmGJOKPuqiDKMqQ6qiB8smHZVVZB6LjDU1HoOIIqC6Atf0DLLAykNUZZXmdhOuIEWvZePFLem91xTX2J37rWqDJllzVrGqv6wJly/qGtXZIeGNjGnWG7M9uygANNvgHrwEyVORE6jMhxPy4zktOnvRlpayR4REZWTz1moZ/ExrXuSN3tAkPGriib1G4Aqm7U1ADI8/RmACx1WUg9jBtNSFZWSt86TWEfNK2kYm3eyfuornjnaFp45Xk6rLwz1Y0fXSRvk2ZcHX8dzbpxkpslKDSshqbGTxfqBk4ZYDO7J7JW3agpWWdSkTt0ustLltlbbdv3p+LDpTG4xpw0Y1tzm6W9dOyY7V9mDIDRl8tceafmZUHyhxMd2oOyhUHXPnlUxoCTZmTGwFT3ST8zBmP8TsmUkmRILguqS1x5ou6SLaaaCN16pzQyZXxwRlRglKunhgIje+aYAj56gtyS7wa7IGmzYNYYSepc4FbtjfElsmskqZoqS0kKR0dSbfW4U7JztAyxDHB6JU31MrFs//R7MREAoGm9VGbqcMFU80EpF8HouHh9BOusNt66TmNyBkthfj1U7DemJX7um6Z7Kpk63IITbb4uQtJEHXK333hFW6CHVfl30c+pXfknA91hJqHf39dpC/Sw6nj1LceO/GsN2qrISLP4/btsePEjg+jj/w==</diagram></mxfile>
```

**Comment by alderg** [comment]
Some of the labels seem to have a font-size CSS rule. Those are overriding the fontSize setting on the shape. The system clock (syclk) label is an example. Try editing, then click </> to see the markup, or replace font-size (not fontSize) in the XML.
