### ISSUE TITLE
Exporting as pdf links back to exp.draw.io 

### ISSUE THREAD

**Issue by poVoq** [jgraph/draw.io#26]
When I try to export an file as .pdf and then click on download or open in new window it links me to the exp.draw.io/ImageExport4/export page. As I am using it on an intranet there is no internet connection.

In addition it would be obviously much preferrable to have everything selfcontained.

Thanks.

**Comment by alderg** [comment]
Use File, Print and Save as PDF for client-side PDF export.

**Comment by poVoq** [comment]
No way to set up our own server side pdf export?

The client side printing as several complications with browsers adding headers and footers etc and also not respecting land-scape/portrait settings. These can be configured but it has to be done manually on every client.

**Comment by alderg** [comment]
We're working on open sourcing the required code, which uses Tomcat and PhantomJS.

**Comment by randrianov** [comment]
hello @alderg, can you share the required code? I write the approach as alternative. Thanks!

**Comment by aptituz** [comment]
@alderg Any progress on open sourcing said code?

**Comment by davidjgraph** [comment]
The bottleneck is me, I have to do legal diligence on everything we open source. It's... on my todo :).

**Comment by aptituz** [comment]
Oh okay, I understand that this takes time. Thanks for your work anyway. :)

**Comment by motohead400** [comment]
Any word on this by chance?

**Comment by 21knowledgePHP** [comment]
Hi
Getting back to you guys. After almost one year did you manage to have Export independent from exp.draw.io. Really eager to develop the PPTx two.

**Comment by poVoq** [comment]
Alternatively, this is a really nice and easy to use pdf export library that could be adapted:
https://github.com/mpdf/mpdf

**Comment by alderg** [comment]
We have open sources it here: https://github.com/jgraph/draw-image-export2
