### ISSUE TITLE
Chrome crashes when open files from google drive

### ISSUE THREAD

**Issue by YukihoAA** [jgraph/draw.io#27]
1. If I and my friend open file from google drive, chrome crashes.
2. When I open file in http://draw.io page, file opens successfully.
3. It only occurs on my, friend's laptop, in my desktop it works fine.

**Comment by YukihoAA** [comment]
I updated my chrome, and it works fine!

**Comment by davidjgraph** [comment]
This is for development issues, do not post usage questions here, post them at https://groups.google.com/forum/#!forum/drawio.
