### ISSUE TITLE
Export as > Save as ... Download does not work on Sandstorm

### ISSUE THREAD

**Issue by ar-jan** [jgraph/draw.io#32]
Using draw.io on Sandstorm (Oasis),  the `Download` button on `Export as` > `Save as` does not work (no download is started, there's no sign anything happens). The `Open in New Window` button in the same dialog does work however, so there is a workaround to get an image or XML export.

P.S. thanks for this nice tool!

**Comment by alderg** [comment]
What browser and version are you using?

**Comment by ar-jan** [comment]
Firefox 50 (on Ubuntu 14.04).

**Comment by alderg** [comment]
Seems to be a problem in FF. Try Chrome.
