### ISSUE TITLE
Cardinality using Crow's foot notation does not rotate according to its proper position

### ISSUE THREAD

**Issue by elmargomez** [jgraph/draw.io#39]
![screenshot from 2016-12-20 13-09-19](https://cloud.githubusercontent.com/assets/12870294/21338988/12dec87c-c6b6-11e6-8805-f4e2b854ec8b.png)

Please refer to Entity 2 and Entity 3, both of them are connected however the foot head is still facing horizontally. I believe it should adjust automatically according to the proper orientation.

**Comment by alderg** [comment]
This is for development issues, do not post usage questions here, post them at https://groups.google.com/forum/#!forum/drawio.
