### ISSUE TITLE
Unable to easily resize currently selected shape while maintaining center

### ISSUE THREAD

**Issue by skewty** [jgraph/draw.io#4]
When a shape is selected, Ctrl + ScrollWheel should resize the shape while maintaining perspective and the center point.

[Ctrl =] and [Ctrl -] should do this too.  [Ctrl 0] to reset to default size.

**Comment by alderg** [comment]
Try Ctrl+Resize (Ctrl+0 is used for custom zoom). Where is Ctrl+Scroll Wheel used for resizing?
