### ISSUE TITLE
Support for NextCloud

### ISSUE THREAD

**Issue by adamtg** [jgraph/draw.io#40]
Is there any chance for getting support for ownCloud/NextCloud?  If not, i am new to web development, but i am an experienced developer, so if i could get some pointers on where the i/o interface is and the API, i would not mind trying to add it in myself.

thank you...

**Comment by adamtg** [comment]
I saw this was already answered at: https://github.com/jgraph/draw.io/issues/10

**Comment by rugk** [comment]
What about just supporting it as "Save as…" option? (and not as a plugin for Own/NextCloud)

**Comment by pawelrojek** [comment]
Here's my NextCloud App (integration): https://github.com/pawelrojek/nextcloud-drawio Check it out.

**Comment by alderg** [comment]
Awesome, thanks for sharing!
