### ISSUE TITLE
embedded image

### ISSUE THREAD

**Issue by gedw99** [jgraph/draw.io#45]
I am using file > export as > SVG
with:
- embed images = true
- include a copy of my diagram = true

i thought that "embed images" would also embed a PNG of the canvas but it seems it does not. Instead it embeds widgets that happen to be images, like clip art for example.
Correct me if i am wrong here.

So, is there a way that a PNG version of the whole diagram can be included ?
For example it could be included as a base64 within the mxfile format.

Why ?
Well we work with SVG, but want to also use the same file with markdown, and so on our server we coudl extract the base64 out of the SVG

**Comment by davidjgraph** [comment]
No, your requirements are not met by the current codebase.
