### ISSUE TITLE
Image blurring on export

### ISSUE THREAD

**Issue by dnviti** [jgraph/draw.io#47]
Hi! I'm an IT Technician on OMA SPA.
We are very excited about using your editor to build an important project, but we are experiencing a lot of problems with raster images (png mostly) because they remain very blurred after export... Is there any way to fix this?
You'll find the self explanatory images below so you can easly notice the differences between original and exported:
Original Image
![original](https://cloud.githubusercontent.com/assets/8649488/21768204/a2e42f76-d678-11e6-90af-b1e0d7628279.PNG)
Imported and then exported with draw.io
![exported](https://cloud.githubusercontent.com/assets/8649488/21768207/a4f10d66-d678-11e6-866e-6723fc4007fb.png)

**Comment by davidjgraph** [comment]
How does any of this relate to draw.io?

**Comment by dnviti** [comment]
The original image is very sharp, but when imported into draw.io and exported in png it becomes very blurry. Is it some king of compression that draw.io makes?

**Comment by davidjgraph** [comment]
Ah, OK. Yes, draw.io compresses larger images by default. Hold shift whilst dragging and dropping the image onto the canvas.

**Comment by davidjgraph** [comment]
Override [EditorUi.prototype.resampleThreshold](https://github.com/jgraph/draw.io/blob/master/war/js/diagramly/EditorUi.js#L70) and
[EditorUi.prototype.maxImageBytes](https://github.com/jgraph/draw.io/blob/master/war/js/diagramly/EditorUi.js#L75) if you want to change it programmatically.

**Comment by dnviti** [comment]
@davidjgraph I changed the two parameters you suggested. The problem is resolved when importing, but when exporting the image is still compressed and then blurred.
I'm testing it in a custom environment using the embedding API.
Here's an example: https://goo.gl/OVgEWa (need to use SHIFT+DRAG here)
In my real working environment there is my server address instead of "https://www.draw.io/".

The thing is: if you download the original image (the one you see when you first open the page), then you open the editor by clicking on it, if on the blank editor page you'll drag-drop the original image and then you'll click on save, you'll see that the image EXPORTED BY THE EDITOR is A LOT smaller than the original one. Can i resolve that issue? It is VERY important for my company to resolve this issue!

**Comment by dnviti** [comment]
Please i'm asking something that is very important for the company where i work and the parameters you suggested me to change are not resolving the issue i'm experiencing.

HERE https://goo.gl/kaMhuJ is an example of the code i used to embed the draw.io editor on my production environment.

If you download the first image you see when opening the page (the original one), then you click on it opening the editor and you import the downloaded image on the editor then click save you'll see that the image you imported has been shrinked to the point that the text IS NO MORE READABLE! That is too much and the people that should use this editor in the company i work cannot use it because of this issue!
