### ISSUE TITLE
Add shapes to Favorites Grouping (saved with File)

### ISSUE THREAD

**Issue by skewty** [jgraph/draw.io#5]
When I right click a shape in the shape selector, I should be able to add it to my favorites.  Then I can expand my favorites and leave the rest collapsed.

I find myself looking through larger groups to find the right shape over and over again.  This is especially time consuming in the network shapes as many look very similar.

**Comment by alderg** [comment]
Use the Scratchpad as explained here: https://support.draw.io/questions/10420280

**Comment by skewty** [comment]
Is there any reason why this feature isn't available on the offline / desktop version?

It isn't showing up unless I go online.

**Comment by alderg** [comment]
This will be fixed in the next release of the Chrome App.
