### ISSUE TITLE
Running draw.io with path

### ISSUE THREAD

**Issue by andersruneson** [jgraph/draw.io#51]
This might be a configuration issue, but I cannot find how to change this.
When running draw.io under a host with path, such as mydraw.io/**editor/** there are some minor issues:
1. When starting the editor i get this: Resource fetch failed (404) https://mydraw.io/img/lib/clip_art/people/Nurse_Man_Red_128x128.png
2. When doing "new" I don't get any templates, in console: GET https://mydraw.io/templates/index.xml 404 (Not Found)

Both those are not using the **editor/** path.

**Comment by alderg** [comment]
Remove the leading slash for TEMPLATE_PATH in Init.js.

**Comment by andersruneson** [comment]
Thanks @alderg, do you mean js/diagramly/Init.js ?
I changed that line but I still get 404 and the console is referring to code in app.min.js
This is the line: window.TEMPLATE_PATH=window.TEMPLATE_PATH||"/templates";
Changing that helps.

I don't even see Init.js being loaded when checking the Sources tab in Chrome developer tools.
The only js files being loaded are app.min.js and jscolor/jscolor.js

**Comment by andersruneson** [comment]
The resource fetch-issue could be because I'm running offline mode and the cache.manifest has path like /img/lib/clip_art/people/Nurse_Man_Red_128x128.png

**Comment by alderg** [comment]
You need to rebuild app.min.js using "ant etc/build/build.xml". The leading slashes in the cache.manifest will be removed.

**Comment by andersruneson** [comment]
Thanks

> The leading slashes in the cache.manifest will be removed.

Did I misunderstand this? cahce.manifest has not changed?
(Also very difficult finding changes to a file when there is a new generation date for each commit without the file changing: [chache.manifest commitlog](https://github.com/jgraph/draw.io/commits/master/war/cache.manifest) )

**Comment by alderg** [comment]
Done. We will move the repo to GitHub ASAP.
