### ISSUE TITLE
Sandstorm.io Self Hosted: Page could not be loaded. Please try refreshing.

### ISSUE THREAD

**Issue by benwinding** [jgraph/draw.io#57]
Fresh installation of sandstorm.io on a private server, all apps work, except this one. There's a lot of bad reviews on the sandstorm page which also mention this error.

[https://apps.sandstorm.io/app/nfqhx83vvzm80edpgkpax8mhqp176qj2vwg67rgq5e3kjc5r4cyh]

A real shame because I love this app, and appreciate the work you guys have put into it. It just doesn't seem to work out of the box.

`Page could not be loaded. Please try refreshing.`

**Comment by davidjgraph** [comment]
Unfortunately, I'm the only one who does the draw.io Sandstorm updating and there's no chance of looking at it in the first half of this year.
