### ISSUE TITLE
Uml insert from text not working

### ISSUE THREAD

**Issue by Zman67** [jgraph/draw.io#58]
Default Uml insert from text is not working

Arrange -> Insert from Text -> Both Plant UML choices

**Comment by alderg** [comment]
Works as expected, please be more specific (NOTE: We use CORS headers and limit the use of this feature to draw.io subdomains.)

**Comment by Zman67** [comment]
try insert this from text on the draw.io <http://draw.io/> site. Its the default text...

**Comment by davidjgraph** [comment]
https://draw.io/ will redirect to https://www.draw.io/ where insert plantuml works.
