### ISSUE TITLE
Option to remove border from box text edition

### ISSUE THREAD

**Issue by erandros** [jgraph/draw.io#61]
When you start the edition mode of a text box, I noticed there's some grey dashed borders applied to each line, also some line-height.  

The problem happens where this causes some overflow when entering edition mode

Not-edition mode:
![image](https://cloud.githubusercontent.com/assets/4072352/22344062/5923fb82-e3d9-11e6-8776-ee04d68bd9e5.png)
Edition mode:
![image](https://cloud.githubusercontent.com/assets/4072352/22344082/6a6b195c-e3d9-11e6-9d23-04b2f7b55406.png)

Is there an option to remove those borders and the same line-height and whatnot so that the entering the edition mode looks the same as the not-edition mode?

**Comment by erandros** [comment]
I could edit this online with some css extension, but I really like using the app because you can save to a local file easier.

**Comment by alderg** [comment]
Use shift-enter to add new lines instead of enter (new paragraph).

**Comment by erandros** [comment]
@alderg that helps, thanks a lot!
