### ISSUE TITLE
Problems with proxy in a draw.io instance running on an own webserver

### ISSUE THREAD

**Issue by pi-log** [jgraph/draw.io#66]
Hello,
 
I am running draw.io in a small web-server (simply deployed the war folder to htdocs) and try to load files from URLs (File->Open->From URL or parameter url=...) on the same web server. This runs into the error "File not found". In the Google (sorry for jumping around - I cannot answer in Google...) group I already got advise to implement a proxy, because draw.io calls the provided URL through a proxy by default:

https://mdraw.io.myorg/folder/draw.io-master/war/proxy?url=https%3A%2F%2Fdraw.io.myorg%2Ffolder%2Ftest.xml

The advise was
"Both of these operations require proxing the data via the server so it's delivered same domain to the client. You either need to use the provided Java Servlet named proxy, or implement a proxy in your preferred server technology."

I have difficulties to check the proxy servlet advice - deployment of draw.io to Tomcat drives me into a SSL_ERROR_RX_RECORD_TOO_LONG dead end.

What about the "preferred server technology" option, what would be the easiest solution, a proxy script? 
I tried to provide a script called "proxy" which used curl to "repeat" the content. However, it works only when the "proxy" is a file containing the xml document. Rather static.

Appreciate any help,

Dieter

**Comment by davidjgraph** [comment]
You have an SSL error on Tomcat, Googling shows http://stackoverflow.com/questions/119336/ssl-error-rx-record-too-long-and-apache-ssl. Have you tried on just http?
