### ISSUE TITLE
cannot login through Google Drive

### ISSUE THREAD

**Issue by ignacio-chiazzo** [jgraph/draw.io#7]
I cannot login through Google Drive. There are an error with cross-origin.

<img width="1209" alt="screen shot 2016-09-24 at 2 57 51 pm" src="https://cloud.githubusercontent.com/assets/11672878/18810237/596d4270-8267-11e6-95ca-1506e710188e.png">

It is happening only in Chrome (Version 53.0.2785.116 (64-bit))
I tried with safari and It works well

**Comment by davidjgraph** [comment]
Github issues are for development issues, not app usage issues.
