### ISSUE TITLE
Github integration doesn't work when user has access to >30 repositories.

### ISSUE THREAD

**Issue by damianh** [jgraph/draw.io#75]
I have access to hundreds of repositories. This dialog needs pagination as it only shows the first 30 or so:

![image](https://cloud.githubusercontent.com/assets/57436/23358599/e911aad8-fce2-11e6-8e53-2a2004e96ba3.png)

Is should also allow filtering if possible. Scrolling through hundreds of line items is not friendly either.

Cheers! :)

**Comment by alderg** [comment]
Thanks for the report, we'll add paging in the next release. (Filtering will have to wait for now.)

**Comment by damianh** [comment]
Great thanks.

**Comment by alderg** [comment]
Fixed in 6.2.2 (added Paging and "Enter Value..." option)
