### ISSUE TITLE
[Feature Request] Include data and object id in svg output

### ISSUE THREAD

**Issue by elliots** [jgraph/draw.io#77]
Hi,

I'm trying to alter the viewer page to allow me to "step through" a component flow diagram, using "step" data values added to objects.

ie. 

![image](https://cloud.githubusercontent.com/assets/622455/23441901/743e694c-fe79-11e6-95e1-1b98cb42eb80.png)

In order to keep context of what to display, it would be great if the data attached in the xml was rendered in the svg. If that is not easy/possible, then having the object ids would make it possible to refer back to the diagram xml to find the data.

Great project btw. Love it.

**Comment by alderg** [comment]
Use the svgdata plugin (via p=svgdata in the URL), it adds an id and content attribute for each cell in the output (see https://github.com/jgraph/draw.io/blob/master/war/plugins/svgdata.js).

**Comment by null-saad** [comment]
> Use the svgdata plugin (via p=svgdata in the URL), it adds an id and content attribute for each cell in the output (see https://github.com/jgraph/draw.io/blob/master/war/plugins/svgdata.js).

Plugin is no more accessible is there any other way to do it?

**Comment by null-saad** [comment]
> Hi,
> 
> I'm trying to alter the viewer page to allow me to "step through" a component flow diagram, using "step" data values added to objects.
> 
> ie.
> 
> ![image](https://cloud.githubusercontent.com/assets/622455/23441901/743e694c-fe79-11e6-95e1-1b98cb42eb80.png)
> 
> In order to keep context of what to display, it would be great if the data attached in the xml was rendered in the svg. If that is not easy/possible, then having the object ids would make it possible to refer back to the diagram xml to find the data.
> 
> Great project btw. Love it.

Juts trying my luck here, cause it's a 2 year old comment, did you find a solution to this?

**Comment by alderg** [comment]
The plugin is here: https://github.com/jgraph/drawio/blob/master/src/main/webapp/plugins/svgdata.js
Load it via https://www.draw.io/?p=svgdata

**Comment by henjoe** [comment]
Hi I know this is an old "Feature Request", May I know how to load this plugin: https://github.com/jgraph/drawio/blob/master/src/main/webapp/plugins/svgdata.js from the 
draw.io? 
When I click the https://www.draw.io/?p=svgdata, it just bring me in here. 

![image](https://user-images.githubusercontent.com/49782655/121105421-aa8ba600-c836-11eb-92a5-677dbf09c2fb.png)

Thank you,

**Comment by awachtler** [comment]
Ping:

Another two years later ... does really nobody need the "id" in a exported SVG?

It would be great to modify the shape attributes and the texts with Java-Script (e.g. in a Dashboard). 

I had even no luck with SvgData-Plugin, it disappeared from the Web.

Maybe a post processing script would be fine too.

**Comment by davidjgraph** [comment]
The first answer is still valid. Add ?p=svgdata to your URL.

**Comment by awachtler** [comment]
Thank you @davidjgraph , it works perfectly. 

Here some screenshots for evidence, in case anybody else stumbles across this thread.

![grafik](https://github.com/jgraph/drawio/assets/21970141/c50d4c91-2c8f-48ee-9b26-e8aef3f83a67)
![grafik](https://github.com/jgraph/drawio/assets/21970141/b2a36414-33c7-4b69-9a80-98276b65d7de)

**Comment by alderg** [comment]
There is now an option in the SVG export dialog:

<img width="398" height="639" alt="Image" src="https://github.com/user-attachments/assets/57354730-5839-4cbd-afb9-eca743ad1664" />
