### ISSUE TITLE
Github integration not working

### ISSUE THREAD

**Issue by metal-gogo** [jgraph/draw.io#81]
Any time I try to commit a diagram to Github it shows a message: "File not found"
![file not found](https://cloud.githubusercontent.com/assets/7268262/23714165/dbb7ccf2-03ed-11e7-8512-eaca7998dd0b.JPG)

**Comment by alderg** [comment]
Are you using any browser extensions? Are there any errors in the console? What browser and version and what operating system are you using? Is the repo public or private?

**Comment by metal-gogo** [comment]
Sorry, my bad... My company network had issues connecting with Github.

**Comment by dcaprani** [comment]
Hi Guys

I'm having exactly the same issue, working from home, no network issues, can access repos directly in GitHub but can't save the draw.io file to a repo I've created for it or any of my existing repos.

![screenshot 2018-01-15 20 26 03](https://user-images.githubusercontent.com/5470445/34960457-ca8f9400-fa32-11e7-9539-e00e040d87f9.png)

**Comment by Pierrocana** [comment]
I have the same issue. The console say "Failed to load Drive Realtime API library.". I am using Firefox 58.0.2 and a plublic repository on github.
