### ISSUE TITLE
draw.io not showing on firefox 52 windows

### ISSUE THREAD

**Issue by ChangePlaces** [jgraph/draw.io#84]
All I see is the top menu along with the message (and yes, js IS enabled!):

Flowchart Maker and Online Diagram Software

draw.io (formerly Diagramly) is free online diagram software. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw.io can import .vsdx, Gliffy™ and Lucidchart™ files .
Loading...

Please ensure JavaScript is enabled

**Comment by alderg** [comment]
Fixed in 6.3.4.
