### ISSUE TITLE
when shadows is enabled, export pdf won't include shadows

### ISSUE THREAD

**Issue by pooyamusavi** [jgraph/draw.io#86]

**Comment by pooyamusavi** [comment]
Try it:
1.Draw some shapes, say some rectangles. Then from View, check shadows (View->Shadows)
2.Now, from File menue click on Export as->pdf. 
3.After downloading, I do not see shadows included!

**Comment by alderg** [comment]
Thanks for the report! This will be fixed in the next release (scheduled for next week).

**Comment by parthjaggi** [comment]
Has this issue been resolved?
Faced this when exporting as PDF.

**Comment by davidjgraph** [comment]
This was disabled for global shadows because they appear pixelated in the PDF, PDF output should all be vector based. Per shape shadows work fine, though.

**Comment by ProviceUnify** [comment]
I found bypass for this problem: export to SVG then "Print to PDF" (adjust orientation, size and scale). Shadows look like in draw.io, but Hatch background kind of cursed:

Final export:
![image](https://github.com/jgraph/drawio/assets/22263818/10912c29-d9b0-4356-91e3-71bb385e2cf7)

Draw.io source:
![image](https://github.com/jgraph/drawio/assets/22263818/de93331a-4143-4d89-a8fa-e703cfc903dc)

It is possible just create sequence to export to SVG then SVG to PDF to avoid make it manually?

**Comment by fumiama** [comment]
Still remains unfixed in the latest v27.0.9, MacOS.
