### ISSUE TITLE
Electron Mac app?

### ISSUE THREAD

**Issue by vilav** [jgraph/draw.io#9]
Hello

I love working with Draw.io since I discovered it recently. Is there any intent to build a Mac app for it, perhaps using the Electron framework? Once reason specifically would be to enable use of the tool when offline.

Thanks

**Comment by davidjgraph** [comment]
There's the package.json and electron.js (the entry JS) in the root https://github.com/jgraph/draw.io/tree/master/war. If you want to progress that please be my guest.

I'll close this issue since it's more just a question.
