### ISSUE TITLE
How to open diagram from draw.io(version 6.4.4) with local server(lasted version 6.4.3)

### ISSUE THREAD

**Issue by kobin3** [jgraph/draw.io#92]
Hello, I already have diagram from draw.io(version 6.4.4) in google drive. I want to open old diagram from google drive but it's said "**This file was created or modified in a newer version of this app. You will be redirected now**.". Can i import or convert old diagram to open with local server or how to find source or builded file of version 6.4.4?

Thank you for you help, and sorry for my bad English.

**Comment by davidjgraph** [comment]
Download the file from drive.google.com (right-click -> download). You can drag and drop the file into a locally running version.
