### ISSUE TITLE
[Feature Request] Export All Pages in one Document

### ISSUE THREAD

**Issue by pensono** [jgraph/draw.io#95]
I would like to be able to export all tabs at once into a single document, primarily for PDF.

The exact implementation of this may look different depending on what format is used, because not all formats support tabs, or multiple pages. In general, the same export box is used as for a sigle page, but the export will create a file with all pages.
- In PDF, the pages exported from individual tabs would be combined into one document.
- Other formats may be exported as a ZIP archive containing a file for each tab. 

In the File menu, the Export option would be renamed "Export Current" or "Export Current Page" and "Export All" or "Export All Pages"

**Comment by pensono** [comment]
I would also like to mention that I may be able to work on this feature

**Comment by andersruneson** [comment]
I would really like Visio export, but maybe that should go in another issue.

My reasons is that we often do drawings for our customers and would like to work in draw.io but hand over the drawings to the customer so they can keep working on them, and "they" always use Visio.

**Comment by alderg** [comment]
This is already available for all formats that support it via the "All Pages" switch. For PDF, use File, Print in draw.io and Save the output as PDF in the browser.

**Comment by pensono** [comment]
Yes, you are correct. For anyone else reading this, it is important to note that if you want a tab that spans multiple pages to be exported to only one, you must check the "Fit to" option rather than the "Adjust"

**Comment by IARI** [comment]
Imho it would be a lot more convenient to be able to just export the whole thing though....

**Comment by gewesp** [comment]
I'd really like this to be re-opened, and if it's only a matter of reducing the number of clicks and/or internet searches the average user has to make.  This is quite a common use case and common use cases should be simple.

**Comment by Stabington** [comment]
+1 for re-opening this.
Would also like to see links to other pages work inside the PDF.

**Comment by itviewer** [comment]
+1 for re-opening this.

**Comment by davidjgraph** [comment]
Since it's a larger block of work, we track larger tasks in Trello. Apply your votes to https://trello.com/c/TZB5LOjw/271-multiple-page-export-in-pdf.

**Comment by NytronX** [comment]
Not signing up to trello, but the vote count should be multiplied by at least four.

**Comment by tu-pm** [comment]
How about exporting all tabs into multiple PNG images? I think it's necessary too.

**Comment by mcflythekid** [comment]
I need to export all tabs, not just the first one

**Comment by davidjgraph** [comment]
I can see a lot of votes for @tu-pm 's comment, however that's not exactly the same thing as the original request. A new issue would be better.
