### ISSUE TITLE
Several Things I dont Like..

### ISSUE THREAD

**Issue by chelinho139** [jgraph/draw.io#96]
Hello draw.io community. There are several things I encountered using draw.io I wish they were different.

1- I cant see the cursor, or what is selected by the other person.
2- I cant chat with the team as I do in google docs (using a chat box).
3- I doesnt have the google look and feel It would be good to respect it.

Sorry it sounds harsh. Best regards.

Cheers.

**Comment by ocdtrekkie** [comment]
As a note from someone who really doesn't like the Google look and feel, I feel inclined to point out that draw.io works on all sorts of platforms that aren't Google Drive as well.

Note that the permission you grant draw.io when you authorize it on your Google account is "View and manage Google Drive files and folders that you have opened or created with this app". It doesn't get access to everything you have in Drive.

**Comment by alderg** [comment]
In addition, in Google realtime, the selection of other users is highlighted and a chat is available via File, Chat.
