### ISSUE TITLE
CSP compatibility

### ISSUE THREAD

**Issue by rugk** [jgraph/draw.io#98]
A [CSP](https://content-security-policy.com/) is a powerful security feature (/header), which can prevent XSS attacks.

However your app is not really compatible with it since you use inline JavaScript and AFAIK also `eval` – both things, which should be avoided for security reasons…

Also, of course, you could suggest/offer a default CSP…

**Comment by alderg** [comment]
We are not using eval.

**Comment by rugk** [comment]
Okay, that's good… 
In the c ode I just [saw it](https://github.com/jgraph/draw.io/search?utf8=%E2%9C%93&q=eval&type=) in jscolor.js and Graph.js, but that was of course only a quick check.

**Comment by alderg** [comment]
Correct, jscolor does seem to use it. In Graph.js we are using eval only for files that are hardcoded into the dynamic stencil loading mechanism.

**Comment by rugk** [comment]
But…, this does not matter for the CSP… :smile: Every eval call will be blocked unless you include `unsafe-eval` in the CSP, which should - as the name implies - be avoided.

**Comment by davidjgraph** [comment]
You're welcome to submit a PR for your suggested changes, but please include an explanation of the precise advantages of the changes, since it's a major change.

**Comment by rugk** [comment]
Of course it is a mayor change and it's a security feature - that's the advantage. Also maybe better maintainability… 😀
Currently I have no plan to create a PR, but maybe later… However, anyone could fix this issue here, it's "only" moving code around.

**Comment by rugk** [comment]
Why not let it open and tag it with "help wanted" or "PR wanted" or so if you have such a tag…
Or just leave it open, so users see this is not fixed/resolved yet.
