### ISSUE TITLE
Qupzilla cannot load draw.io locally

### ISSUE THREAD

**Issue by geiseri** [jgraph/draw.io#99]
If I try to load draw.io from the local disk for some reason [qupzilla](https://www.qupzilla.com/) cannot run it.  I see the error below:
![loaderror](https://cloud.githubusercontent.com/assets/2265693/25362419/c70c8ad2-2921-11e7-9ac9-b099190f5675.png)
no matter how many times I try to refresh nothing happens.  What is odd is I do not see any errors in the debugger.  The only console message I see is about a synchronous xhr request.  If I try to use firefox, msie and edge it will work as advertised. Are there any quirks that I cannot see if I am using it on the local filesystem?  If I run it from an actual https server it also works as advertised.  Is there any way I can get more debugging information?

**Comment by geiseri** [comment]
I captured the network load timeline and found something very strange.  It takes 20 seconds to load the shapes.min.js from the local file-system.

![loadtimeline](https://cloud.githubusercontent.com/assets/2265693/25362857/74abd3e4-2924-11e7-8c62-76239817a086.png)

So something definitely is going on strange when things load from the local file-system in that browser.  I do not see the same behavior at all on edge.

**Comment by davidjgraph** [comment]
You can't develop apps that use XHR from the filesystem, https://productforums.google.com/forum/#!topic/chrome/v177zA6LCKU
